### ISSUE TITLE
After few time server just stop response

### ISSUE THREAD

**Issue by ArtNRG** [StargateMC/Regenerator#10]
I have test server git-Paper-1104 (MC: 1.11.2) with 4 plugins:
Regenerator v3.2.3
GriefPrevention v16.6
Multiverse-Core v2.5.0-SNAPSHOT-b725
LagMonitor v1.14

I have no any errors, cache chunk maps is turned off.
Look at the log that i see after few minutes:
[07:40:00 INFO]: Current TPS: 19.417477
[07:42:15 INFO]: Current TPS: 3.0792918
[07:47:40 INFO]: [Regenerator] [INFO]: Regeneration task is starting...
[07:48:53 INFO]: Current TPS: 2.7498968

The server use 100% RAM in the moment - about 3.5 GB.

Full log: https://pastebin.com/T4Dg7vsT
Global.yml: https://pastebin.com/1vC9HzmA

Regenerating is turned on only in 1 world. In data folder i have manually create world.yml file like that:
chunks:
  568,385: 0
  568,386: 0
  568,387: 0
  568,388: 0
  ....
There are about 20 thousands lines there, because i expect that there will be the same file after few days working on the live server.
If you need any additional information, just let me know.

**Comment by StargateMC** [comment]
Whats the specifications of your server? Is it dedicated? Virtual?
If you look at the logs, something is causing a lag spike before Regenerator starts doing anything, which tells me this isn't a problem on my end. 
You shouldn't run a server that requires 100% of your available memory anyway.

Closing because this is not a regenerator issue, looks like you need to upgrade the hardware you're running on.

See this from your logs: `[08:19:35] [Craft Scheduler Thread - 5/INFO]: [Regenerator] [INFO]: Regenerator is not beginning to parse inactive chunks as the TPS is below 15 (defined in global.yml).`
